### ISSUE TITLE
Stack of notifications

### ISSUE THREAD

**Issue by PSDCoder** [matowens/ng-notify#13]
Now only one notification can be displayed simultaneously.
But what do you think about feature of stacking of few messages?

**Comment by tcdevs** [comment]
@PSDCoder i think that you better can try https://github.com/jirikavi/AngularJS-Toaster this will support stacking out of the box. Hope that helps.

**Comment by yftachman** [comment]
Not super simple, but i think it's do-able.
I'll try to get on it this weekend.

**Comment by PSDCoder** [comment]
@tcdevs I know about angularjs-toaster and angular-toastr, but would like to see this feature in this module.
@yftachman Thanks!

**Comment by matowens** [comment]
@PSDCoder I've thought about adding that in the past.  I'm not a big fan of trying to stack messages with the current full width format - I think it could lend to a bad user experience if half the screen is piling up notifications, but I have thought about adding a new option for a stack type of message that could be positioned towards each of the corners, similar to toaster as @tcdevs has mentioned.  Is that sort of what you were thinking as well?

@yftachman sounds good, would love to see what you come up with!

**Comment by yftachman** [comment]
That's thr least of my worries. NgNotify relies on there being only one notification object. We have to change it so it will be able to manage notification objects.

But im guessing that adding a class that handles the width is not going to be a problem.

**Comment by PSDCoder** [comment]
@matowens Yeap, maybe in current format it will be not good. We can change positioning with width, as you suggest, or we can store in stack all notifications, but show simultaneously only 3 for example, after closing one - we show next.  Also we can decrease vertical paddings. We can try different variants.

**Comment by yftachman** [comment]
A quick update:
i tried to do this today.
theres seems to be a lot of problems
i've tried to use an ng-repeat inside the template.
took a few hours till i got that working but now its seems we have a new problem with the fadeLib.

in my opinion the logic and the ui are too coupled to eachother.
it might be better to extract the fadeLIb into a directive, this way we can handle the data of notifications (# of notification present and properties of each notification) and let the angular do all the heavy lifting regarding the ui.

but this means extensive changes to this library, i would like to hear what are you thoughts on the issue.

you can view my changes in my fork in the develop branch: 
https://github.com/yftachman/ng-notify

**Comment by yftachman** [comment]
worked on it a little more today.
it works but has some bugs with sticky notifications and needs a little clean up
