### ISSUE TITLE
Default configuration

### ISSUE THREAD

**Issue by sylouuu** [matowens/ng-notify#16]
Hey,

Thanks for ng-notify.

I'm wondering where do you put `ngNotify.config()`? In a controller?

For some other ng plugins that I've to use, all default options are inside:

```js
app.config(function ($somethingProvider) {
    $somethingProvider.options({ ... });
});
```

But I can't inject ngNotify there, same in `app.run()`.

So how do you do?

Bests

**Comment by jasmeetssalech** [comment]
Thanks for ng-Notify. Works like a charm.

I am having the same question as sylouuu

**Comment by matowens** [comment]
Hey guys, if you'd like to setup some default config options I'd recommend tossing it in the `.run()` block.  There isn't much info from the docs on it, but [here's a snippet](https://docs.angularjs.org/guide/module#run-blocks).

A working example of setting it up this way:

```
<html ng-app="testApp">
<head>

    <link rel="stylesheet" type="text/css" href="ng-notify.min.css" />

</head>
<body ng-controller="homeController">

    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js"></script>
    <script src="ng-notify.min.js"></script>

    <script>

        // Intialize app.
        var app = angular.module('testApp', ['ngNotify']);

        // Set global config up on run.
        app.run([
            'ngNotify',
            function(ngNotify) {

                ngNotify.config({
                    position: 'top',
                    sticky: 'true'
                });
            }
        ]);

        // Use notify anywhere else.
        app.controller('homeController', [
            'ngNotify',
            function(ngNotify) {

                ngNotify.set('ngNotify default config options have been overriden.');

            }
        ])

    </script>

</body>
</html>
```

Here's an example you can play around with [on codepen](http://codepen.io/matowens/pen/BNLrzL/?editors=001).

If you have a global controller, you could toss it in there as well.  Hope this helps ya out!

**Comment by sylouuu** [comment]
@matowens You have right, my bad, it works in `app.run()`.

But it's the first time I see a plugin configuration inside `app.run()` instead of `app.config()`.

**Comment by gusbicalho** [comment]
The configuration is in .run() because the configuration methods are in the
service itself, not in the service's provider. That means you can change
the defaults while the app is running (in a Controller, for example), and
you can access other services when you do that.
In this case I don't think that's a bad idea. The provider should only be
used for configurations that have to happen before the app starts running.

**Comment by sureshanand** [comment]
very Nice
