### ISSUE TITLE
dismiss(), opacity didn't stop at 0

### ISSUE THREAD

**Issue by Droritos** [matowens/ng-notify#18]
I don't know what happened, but I noticed after dismissal that the notification never showed back when calling set() again. So I went the developer tools and saw the opacity value rapidly decreasing in value. Of course, the CPU went up like crazy.

See attached image.
![untitled](https://cloud.githubusercontent.com/assets/13335376/8677487/fdec7320-2a57-11e5-9159-123812b7bb1a.png)

EDIT:
It seems to happen whenever I set() and dismiss() very fast.

**Comment by Droritos** [comment]
For anyone that might need it, here's what I did. Works perfectly now.

1) Add helper flags.
var notifyShown = false;
var notifyDismissing = false;

2) 
notifyScope.dismiss = function () {
    notifyDismissing = true;

    fadeOut(FADE_OUT_DURATION, function() {
    notifyReset();
    notifyShown = false;
    notifyDismissing = false;
    });
};

3) 
return {
    set: function(message, userOpt) {
        ...
        if (angular.isDefined(notifyTimeout)) {
                $timeout.cancel(notifyTimeout);
                notifyTimeout = undefined;
        }

        if (angular.isDefined(notifyInterval)) {
                $interval.cancel(notifyInterval);
                notifyInterval = undefined;
        }
    
        ...
        fadeIn(FADE_IN_DURATION, function() {
            notifyShown = true;
            if (isSticky) {
                ...
            }
        }
    }
4) 
    dismiss: function () {
        if (notifyShown && !notifyDismissing) {
            notifyScope.dismiss();
        }
    },

**Comment by nzamosenchuk** [comment]
Hi Droritos! 
Looks similar to the problem I also discovered. When notifications where constantly shown or constantly hidden with opacity going to +inf or -inf.

https://github.com/matowens/ng-notify/issues/17

Waiting for Mat ...

**Comment by matowens** [comment]
Gonna close this one out since we're addressing it over on #17.
