### ISSUE TITLE
disable close button for sticky

### ISSUE THREAD

**Issue by programming-kid** [matowens/ng-notify#21]
i use ng-notify  in all my projects its clean n simple , just the way it should be , there is just one minor aesthetic thing which bothers me is, there is a close button during sticky,  i agree its useful in many situation but sometime there are instance where it feels more right not to have it , where you would like to programmatically  dismiss it after certain events occurred.

I wish it could be included in config

thanks

**Comment by maksad** [comment]
+1

**Comment by matowens** [comment]
Hey guys, I've added a param called `button` to the config.  By default it's set to true, but if the message is sticky and you'd like to prevent the button from appearing, you can set button to false.  Eg:

    ngNotify.set('This is sticky without a button.', {
        sticky: true,
        button: false
    });

Thanks for the feedback, it's much appreciated.  Hope this helps ya out!

**Comment by programming-kid** [comment]
that's great @matowens  thanks man :+1:
