### ISSUE TITLE
Angular 1.5

### ISSUE THREAD

**Issue by solo12zw74** [matowens/ng-notify#26]
Is `ng-notify` compatible with Angular 1.5 and higher? If it is - please update bower.json file dependencies section. bower can not install package if angular 1.5 installed

**Comment by matowens** [comment]
Hey Solo, yup it's compatible with 1.5, I'll get that updated.  Thanks for pointing it out!

**Comment by matowens** [comment]
@solo12zw74 should be ready to roll.  let me know if you have any issues.  thanks again.
