### ISSUE TITLE
Callback after notify fadeout

### ISSUE THREAD

**Issue by qoshi** [matowens/ng-notify#30]
I want to do something after the notify fadeout but after I read the code I could hardly find out a way to do so. So, will u do that?

**Comment by matowens** [comment]
Do you mind showing me an example of what you're looking to do in your code?  Perhaps something like this?

```
var callback = function() { 
    console.log('do this after fading'; 
};

ngNotify.set('My message.', [], callback);
```

**Comment by matowens** [comment]
Also, just curious, what sort of thing were you wanting to do after displaying the error?
