### ISSUE TITLE
Html button event

### ISSUE THREAD

**Issue by danielemontesi** [matowens/ng-notify#37]
How can i insert html button and add ng-click event? I do thath 

`ngNotify.set('<button class="btn btn-sm btn-default" ng-click="test();"><i class="fa fa-times"</i>No</button>', { type: 'info', sticky: true, button: true });`

but does not work

**Comment by matowens** [comment]
You're not able to pass through a template and scope as the message.  It's expecting a string that it can just append to an element to display to the user.

If you're looking to trigger a function call after the user closes the message, you should be able to pass in your function as a callback in the set() method like this:

```
var callback = function() { alert('show this when the user closes the message'); };

ngNotify.set('Message to user', { type: 'info', sticky: true, button: true }, callback);
```
