### ISSUE TITLE
integrate with form validation?

### ISSUE THREAD

**Issue by theaccordance** [matowens/ng-notify#40]
More of a question than an issue, is it possible to integrate the `ng-notify` to work with angular form validation?  Id like to keep my user notifications uniform using the module if possible.

**Comment by matowens** [comment]
That's a good question.  How are you thinking of using the two pieces together?  Showing inline validation for each specific form field while displaying a generic error message in an ng-notify notification that tells the user to correct any errors that they might see in the form?

If you were going to set something up for that use case, you could watch the validity of the form and if it ever triggered an invalid state, you could display a message.  

There's an example of watching validity here where you could add your notification to: http://stackoverflow.com/questions/15899389/angularjs-directive-watch-validity
