### ISSUE TITLE
ngNotify circular reference error when accessing in http interceptor

### ISSUE THREAD

**Issue by atul221282** [matowens/ng-notify#41]
I really like this service an thought of using it to display error globally. To use it globally I created http interceptor and registered it in config but when I try to inject ngNotify in my http interceptor i keep getting circular reference error

my config
angular.module("commonModule", ["ui.router", "ngNotify"]);

```
angular.module("commonModule").config(config);
config.$inject = ["$httpProvider"];//, "$stateProvider", "$urlRouterProvider", "$locationProvider"];

function config($httpProvider) {//, $stateProvider, $urlRouterProvider, $locationProvider) {
    $httpProvider.interceptors.push('HttpResponseInterceptor');
};
```

})();

and my http interceptor is

(function (commonModule) {

```
'use strict';

commonModule.factory("HttpResponseInterceptor", HttpResponseInterceptor);

HttpResponseInterceptor.$inject = ["$q", "ngNotify"];
function HttpResponseInterceptor($q, ngNotify) {
    var deferred = $q.defer();
    return {
        responseError: function (response) {
            deferred.reject(response);

            return deferred.promise;
        }
    }
};
```

})(angular.module("commonModule"));

**Comment by RootsMJ** [comment]
+1 I have the same issue.

**Comment by guylhermetabosa** [comment]
I had the same problem a while ago. Using $injector solved to me.

**Comment by atul221282** [comment]
Yeah use $injector to resolve dependency. I forgot to give an answer my bad

**Comment by gsonego** [comment]
I did the same as @atul221282... using $injector inside function body instead of passing by function parameter works like a charm!
.
.
```
    app.factory("httpInterceptor", function ($q, $rootScope, $injector) {
        return {
            responseError: function (response) {
                var notificationService = $injector.get("ngNotify");

                var config = configNotification(response.status);
                notificationService.set(config.message, 'error', config.callback);
```
.
.

**Comment by atul221282** [comment]
Closing it as no progress is happening here.
