### ISSUE TITLE
Having the notification appear for wait

### ISSUE THREAD

**Issue by zeeshanjan82** [matowens/ng-notify#8]
How can I have the notification appear as long as I am waiting for the current operation to return status like an ajax call. All the examples have a predefined time which we can set. Is there any setting where I want the notification to appear as long as I want and when I have result from the ajax call then I can hide the notification.

**Comment by matowens** [comment]
@zeeshanjan82 you could give the sticky notifications a try. - https://github.com/matowens/ng-notify#sticky-notifications

Set sticky to true, and then when your promise is resolved, you could call the dismiss() method to close the notification when you're ready to.

**Comment by guylhermetabosa** [comment]
@matowens in iOS, I'm using this statregy however the notifications isn't fading out. I opened an issue #48 for this.
